#!/bin/bash
hash preml 2>&- || { echo >&2 "PreML is not installed.  Aborting."; exit 1; }
hash mlton 2>&- || { echo >&2 "MLTon is not installed.  Aborting."; exit 1; }
if [ $1 ]; then
   preml "$1"
   echo "Preprocessing done.  Running mlton."
   mlton -output "`dirname $1`/`basename "$1" .mlb`" "$1.premlfile.mlb"
   # A hack for now..
   rm -r `dirname $1`/*.premlfile.* 2> /dev/null
else
   echo "Usage: $0 [file]"
fi

